### ISSUE TITLE
.net core 3.1 (cant open ego erp)

### ISSUE THREAD

**Issue by emirggl** [ptasev/Ego-Engine-Modding#45]
i downloaded .net core 3.1 but still icant open ego erp archiver
![Screenshot_1](https://user-images.githubusercontent.com/69692906/90280488-ad667600-de73-11ea-9077-d57a39f223aa.png)

**Comment by BenW40** [comment]
I'm having the same issue, I saw elsewhere that turning off the MSI afterburner overlay can make it work but I'm not running that program so I'm lost

**Comment by harryfarinuddin** [comment]
I'm having the same Issue, please help!

**Comment by JohnTolv** [comment]
I found a solution, for my problem at least. The problem was that when i installed the latest version of .NET core, it installed .NET Core 3.1.7

Ego ERP Archiver however, looked for the file path to .NET Core 3.1.0

I downloaded 3.1.0 via this [link](https://dotnet.microsoft.com/download/dotnet-core/3.1) where you can download older versions!

https://dotnet.microsoft.com/download/dotnet-core/3.1

**Comment by emirggl** [comment]
i downloaded every versions of .net core but surprisingly it didn't work sooo

**Comment by ptasev** [comment]
Make sure that you are installing the appropriate version for your computer. For example if you are using Windows 64 bit then download the x64 installer.

**Comment by emirggl** [comment]
yeah i redownloaded destkop runtime x64 and it worked. Thanks all the advice!!!
